### ISSUE TITLE
:not()

### ISSUE THREAD

**Issue by mefynn** [drewhamlett/brackets-beautify#156]
This css pseudo selector is beeing seperated as ": not()" on beautify in the current version. 
please release a fix. 
greetings fynn

**Comment by derwaldgeist** [comment]
Same goes for :nth-child which breaks the Sass parser. Seems as if all pseudo selectors are affected.

**Comment by phillip-haydon** [comment]
beautify-web/js-beautify#706

This has been fixed and will be in the next version of js-beautify v1.5.7

@drewhamlett FYI :)

<3

**Comment by derwaldgeist** [comment]
Thanks!

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md#v157

**Comment by derwaldgeist** [comment]
This still does not work for:
:not(:first-child)
Results in:
:not( :first-child)
which is breaking Sass compilation

**Comment by bitwiseman** [comment]
@derwaldgeist, please make sure there's a new issue filed with js-beautify for this.

**Comment by drewhamlett** [comment]
This is fixed in 1.2.0.  So sorry for delay
